[package]
name = "uros"
version = "0.1.0"
authors = ["Jonathan Schenk <jds8899@rit.edu>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0"
spin = "0.5.0"

[dependencies.lazy_static]
version="1.0"
features = ["spin_no_std"]
